[package]
name = "playout-rs"
version = "0.1.0"
authors = ["superlou <lousimons@gmail.com>"]

[dependencies]
gstreamer = "0.7.1"
bytes = "0.4"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
regex = "0.2"
