[package]
name = "playout-gui"
version = "0.1.0"
authors = ["superlou <lousimons@gmail.com>"]

[dependencies]
gdk = "0.5.3"
gtk = "^0.1.2"
relm = "0.9.6"
relm-derive = "^0.9.2"
relm-attributes = "^0.9.0"
chrono = "0.4.0"
simplelog = "0.4.2"
libc = "0.2.0"
gstreamer = "0.7.1"
